#!/usr/bin/env python3
"""asm_emit_blob.py -- emit object1 as ONE relocatable native blob (the runnable model).

The per-function emitter (asm_emit_all.py) is great for a mixed C/asm build, but it places
functions at linker-chosen addresses, so absolute code pointers (switch jump tables, function
pointers -- 1854 obj1 fixups) can't be a simple base+offset. Keeping the WHOLE code segment
contiguous at its original relative offsets fixes that for free: every intra-code relative
call/jump stays valid, and every absolute code pointer is `__obj1 + offset` with __obj1 = the
blob base. Only references that LEAVE the blob need symbols: the DGROUP data (obj2/3/4).

This is origbuild's model (which produces a working DOS binary) as a native ELF/PE object.

Emits port/gen/blob/game_blob.s:
  __code: <261620 bytes of obj1, verbatim except 4-byte fixup slots ->  .long __obj<N> + off>
  plus `.set <funcname>, __code + (addr - 0xd748)` for every manifest function (call handles).

Verify (byte-identity): assemble with __obj1..4 = 0 and the .text must equal obj1_full.bin
(every object-relative placeholder reproduced).

Usage:
  python tools/asm_emit_blob.py            # emit the blob .s + a function-symbol include
  python tools/asm_emit_blob.py --verify   # emit + assemble with bases=0 + compare to obj1_full.bin
"""
import os, re, sys, json, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OBJ1 = os.path.join(ROOT, "build", "obj1_full.bin")
CODE_BASE = 0xd748            # obj1_full.bin manifest base
LE_SHIFT = 0x28b8            # manifest = LE - 0x28b8 ; obj1 LE base 0x10000
IS_WIN = sys.platform == "win32"
GEN = os.path.join(ROOT, "port", "gen", "blob")
US = ""                      # symbol prefix; "_" for Windows COFF (leading-underscore convention)

def sh(cmd):
    argv = ["wsl", "bash", "-c", cmd] if IS_WIN else ["bash", "-c", cmd]
    return subprocess.run(argv, capture_output=True, text=True)

def envpath(p):
    if not IS_WIN:
        return p
    return subprocess.run(["wsl", "wslpath", "-a", p.replace("\\", "/")],
                          capture_output=True, text=True).stdout.strip()

def all_fixups():
    """{manifest_source_off: (objn, toff, add)} for every type-7 code fixup."""
    out = subprocess.run([sys.executable, os.path.join(ROOT, "tools", "lefix.py"),
                          "src", "%x" % CODE_BASE, "0x42000"], capture_output=True, text=True).stdout
    fx = {}
    for line in out.splitlines():
        m = re.match(r"src=0x([0-9a-fA-F]+)\s+stype=7\s+ttype=\d+\s+->\s+obj(\d):\+0x([0-9a-fA-F]+)\s+add=(\S+)", line)
        if m:
            fx[int(m.group(1), 16)] = (int(m.group(2)), int(m.group(3), 16),
                                       None if m.group(4) == "None" else int(m.group(4), 0))
    return fx

def func_addrs():
    m = {}
    for f in json.load(open(os.path.join(ROOT, "manifest", "functions.json")))["functions"]:
        try:
            m[f["name"]] = int(f["addr"], 16)
        except (KeyError, ValueError):
            pass
    return m

def emit(shims=None):
    """shims: set of function names to REDIRECT to an external C shim -- their blob entry is
    overwritten with `jmp <name>` (5 bytes), so intra-blob relative calls reach the shim, which
    returns to the original caller. Shimmed names are NOT given a `.set` handle (they resolve to
    the external shim)."""
    shims = shims or set()
    os.makedirs(GEN, exist_ok=True)
    img = open(OBJ1, "rb").read()
    fx = all_fixups()
    faddr = func_addrs()
    # blob offset -> shim name, for each shimmed function present in the image
    shim_at = {faddr[n] - CODE_BASE: n for n in shims if n in faddr and faddr[n] >= CODE_BASE}
    # blob offset -> function name, so every function is a real label defined IN the blob
    # (a `.set name, __code+off` in a separate object does not resolve -- as can't evaluate the
    # external __code at assembly time).
    sym_at = {}
    for name, a in faddr.items():
        if a >= CODE_BASE:
            sym_at.setdefault(a - CODE_BASE, []).append(name)
    lines = ["/* generated by tools/asm_emit_blob.py -- object1 as one relocatable blob */",
             "    .text",
             "    .globl %s__code" % US, "    .globl %s__obj1" % US,
             "    .set %s__obj1, %s__code" % (US, US),
             "%s__code:" % US]
    pend = []
    def flush():
        while pend:
            ch = pend[:16]; del pend[:16]
            lines.append("    .byte " + ",".join("0x%02x" % b for b in ch))
    n = len(img)
    i = 0
    while i < n:
        o = CODE_BASE + i
        if i in sym_at:
            flush()
            for name in sym_at[i]:
                # prefix with game_ so the 663 function symbols don't collide with libc names
                # (open/read/write/close/system/strchr/...), which the C shims call.
                lines.append("    .globl %sgame_%s" % (US, name))
                lines.append("%sgame_%s:" % (US, name))
        if i in shim_at and i + 5 <= n:
            flush()
            name = shim_at[i]
            lines.append("    /* shim: %s -> shim_%s (external C) */" % (name, name))
            lines.append("    .byte 0xe9")               # jmp rel32 to the shim
            lines.append("    .long %sshim_%s - . - 4" % (US, name))
            i += 5
        elif o in fx and i + 4 <= n:
            flush()
            objn, toff, add = fx[o]
            e = "%s__obj%d + 0x%x" % (US, objn, toff)
            if add:
                e += " + 0x%x" % add
            lines.append("    .long %s" % e)
            i += 4
        else:
            pend.append(img[i]); i += 1
    flush()
    if not US:                                  # ELF-only note; MinGW/COFF as rejects it
        lines.append("    .section .note.GNU-stack,\"\",@progbits")
    open(os.path.join(GEN, "game_blob.s"), "w").write("\n".join(lines) + "\n")
    # (function entry symbols are emitted as real labels inside the blob above)
    return len(fx), n

def verify():
    nfx, nbytes = emit()
    os.makedirs(GEN, exist_ok=True)
    dw = envpath(ROOT)
    sp = dw + "/port/gen/blob/game_blob.s"
    op = dw + "/port/gen/blob/game_blob.o"
    ep = dw + "/port/gen/blob/game_blob.elf"
    bp = os.path.join(ROOT, "port", "gen", "blob", "game_blob.bin")
    bpw = dw + "/port/gen/blob/game_blob.bin"
    r = sh("as --32 -o '%s' '%s'" % (op, sp))
    if r.returncode:
        print("assemble FAILED:\n" + r.stderr[:2000]); return False
    # link at the original base with all __obj bases = 0 -> reproduces placeholders
    r = sh("ld -m elf_i386 --defsym __obj1=0 --defsym __obj2=0 --defsym __obj3=0 --defsym __obj4=0 "
           "-Ttext=0x%x -e __code -o '%s' '%s'" % (CODE_BASE, ep, op))
    if r.returncode:
        print("link FAILED:\n" + r.stderr[:2000]); return False
    sh("objcopy -O binary --only-section=.text '%s' '%s'" % (ep, bpw))
    got = open(bp, "rb").read()
    want = open(OBJ1, "rb").read()
    if got == want:
        print("BLOB-OK: %d bytes byte-identical (%d fixups symbolized)" % (nbytes, nfx))
        return True
    n = min(len(got), len(want))
    for j in range(n):
        if got[j] != want[j]:
            print("MISMATCH at +0x%x: got %02x want %02x (len got=%d want=%d)"
                  % (j, got[j], want[j], len(got), len(want)))
            return False
    print("LENGTH differs: got=%d want=%d" % (len(got), len(want)))
    return False

def read_shim_list():
    """--shims name1,name2,...  or  --shims-file path (one name per line)"""
    shims = set()
    for i, a in enumerate(sys.argv):
        if a == "--shims" and i + 1 < len(sys.argv):
            shims |= {s for s in sys.argv[i + 1].split(",") if s}
        if a == "--shims-file" and i + 1 < len(sys.argv):
            shims |= {ln.strip() for ln in open(sys.argv[i + 1]) if ln.strip() and not ln.startswith("#")}
    return shims

if __name__ == "__main__":
    if "--underscore" in sys.argv:              # Windows COFF leading-underscore convention
        US = "_"
    if "--verify" in sys.argv:
        sys.exit(0 if verify() else 1)
    shims = read_shim_list()
    nfx, nbytes = emit(shims)
    print("emitted %s/game_blob.s (%d bytes, %d fixups, %d shims) + game_syms.s"
          % (GEN, nbytes, nfx, len(shims)))
