#!/usr/bin/env python3
"""port_bringup.py -- native-build bring-up for the `port` branch.

Compiles the portable game-logic C (src/**, excluding src/lib asm and db-byte transcriptions),
collects the undefined symbols, and generates:
  port/gen/globals.c   -- a definition for every undefined g_* global (BSS placeholder; the
                          real DGROUP-image data model is a later step -- see NOTE below)
  port/gen/stubs.c     -- a weak no-op definition for every undefined FUNCTION at the platform/
                          lib boundary, so the binary LINKS before the SDL shim exists
  port/gen/main.c      -- a trivial entry that inits the stub platform and returns
Then links a native `port/build/syndicate` to prove the pipeline end-to-end.

NOTE: globals here are independent BSS arrays, so overlapping field-views (g_syndicate_owner ==
g_syndicate_recs+2) do NOT alias -- the binary LINKS and starts but does not play correctly yet.
Correct execution needs the DGROUP data image + address-placed globals (the next bring-up step).
Run in the synd-decomp container OR any box with gcc.
"""
import glob, re, os, subprocess, sys, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "port", "gen")
os.makedirs(GEN, exist_ok=True)

def game_logic_files():
    out = []
    for p in sorted(glob.glob(os.path.join(ROOT, "src", "**", "*.c"), recursive=True)):
        rel = p.replace("\\", "/")
        d = "/".join(rel.split("/src/")[1].split("/")[:-1])
        if d.startswith("lib"):
            continue
        t = open(p, encoding="utf-8", errors="ignore").read()
        if re.search(r'#pragma aux', t) or '__far' in t or ':>' in t or 'int386' in t or re.search(r'\b(inp|outp)\b', t):
            continue
        out.append(p)
    return out

def main():
    files = game_logic_files()
    obj = os.path.join(GEN, "obj"); os.makedirs(obj, exist_ok=True)
    for f in glob.glob(obj + "/*.o"):
        os.remove(f)
    objs = []
    for i, f in enumerate(files):
        o = os.path.join(obj, "o%d.o" % i)
        if subprocess.run(["gcc", "-c", "-w", "-o", o, f]).returncode == 0:
            objs.append(o)
    print("compiled %d/%d game-logic objects" % (len(objs), len(files)))
    # first link pass to collect undefined symbols
    r = subprocess.run(["gcc", "-o", os.path.join(GEN, "syn"), *objs], capture_output=True, text=True)
    undef = sorted(set(re.findall(r"undefined reference to `([^']+)'", r.stderr)))
    g = [s for s in undef if s.startswith("g_")]
    fns = [s for s in undef if not s.startswith("g_") and s != "main"]
    print("undefined: %d globals, %d functions" % (len(g), len(fns)))
    # generate globals.c (BSS placeholders; size from globals.json type where known, else 256)
    reg = json.load(open(os.path.join(ROOT, "manifest", "globals.json")))
    byname = {k: v for k, v in reg.items()}
    with open(os.path.join(GEN, "globals.c"), "w") as w:
        w.write("/* generated by tools/port_bringup.py -- BSS placeholders, NOT the real DGROUP\n"
                "   data model. Overlapping field-views do not alias yet. */\n")
        for s in g:
            w.write("unsigned char %s[256];\n" % s)
    # generate stubs.c (weak no-op functions returning 0)
    with open(os.path.join(GEN, "stubs.c"), "w") as w:
        w.write("/* generated: weak no-op boundary stubs so the native build LINKS.\n"
                "   Replace with the SDL platform shim (video/input/audio/timer) + ported CLIB. */\n")
        for s in fns:
            w.write("int %s(){return 0;}\n" % s)
    with open(os.path.join(GEN, "main.c"), "w") as w:
        w.write('#include <stdio.h>\nint main(void){printf("syndicate native (stub platform)\\n");return 0;}\n')
    # final link
    out = os.path.join(ROOT, "port", "build"); os.makedirs(out, exist_ok=True)
    exe = os.path.join(out, "syndicate")
    r2 = subprocess.run(["gcc", "-w", "-o", exe, *objs,
                         os.path.join(GEN, "globals.c"), os.path.join(GEN, "stubs.c"),
                         os.path.join(GEN, "main.c"), os.path.join(ROOT, "port", "platform_stub.c")],
                        capture_output=True, text=True)
    if r2.returncode == 0:
        print("=== LINKED: %s (%d bytes) ===" % (exe, os.path.getsize(exe)))
        rr = subprocess.run([exe], capture_output=True, text=True)
        print("run:", rr.stdout.strip())
    else:
        print("=== LINK FAILED ===")
        print(r2.stderr[-1500:])

if __name__ == "__main__":
    main()
