#!/usr/bin/env python3
"""port_dgroup.py -- emit the DGROUP data image with data-internal POINTERS relocated.

The game's DGROUP data holds pointers (string tables, data->data and data->code pointers)
stored as object-relative placeholders. The DOS loader fixes them up via the LE fixup table;
the native build must too, or the first pointer dereferenced (a string in set_message_line)
is null. This emits the data image as an assembly object where every such pointer is a
`.long __obj<N> + offset` -- so the native linker relocates them, exactly like the code blob.

Uses the FULL LE object pages (origbuild.le_object_data), not the *.linear.bin extracts that
drop each object's first 0x28b8 bytes.

DGROUP layout (obj bases = cumulative vsizes): obj2 @ 0, obj3 @ 0x13e60, obj4 @ 0x14a60.
Emits port/gen/blob/dgroup_full.bin (image) + port/dgroup.s (incbin slices + .long fixups).
"""
import os, sys, struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import lefix
import origbuild

GEN = os.path.join(ROOT, "port", "gen", "blob")
US = "_" if "--underscore" in sys.argv else ""   # Windows COFF leading-underscore convention
SEGLEN = 0x109110                       # cover the high globals (matches port_data.py)
OBJ_DG_BASE = {2: 0x0, 3: 0x13e60, 4: 0x14a60}   # DGROUP offset of each object
# source-linear base of each data object = LE base - e_lfanew(0x28b8)
OBJ_SRC_BASE = {2: 0x50000 - 0x28b8, 3: 0x70000 - 0x28b8, 4: 0x80000 - 0x28b8}

def src_object(src_lin):
    """Which object a fixup SOURCE lies in (obj1 code < 0x4d53c; obj2/3/4 data above)."""
    if src_lin < 0x4d53c:
        return 1
    for objn in (2, 3, 4):
        base = OBJ_SRC_BASE[objn]
        if base <= src_lin < base + 0x20000:   # generous; refined by vsize below
            return objn
    return None

def main():
    os.makedirs(GEN, exist_ok=True)
    _, objs, fixups = lefix.parse()
    vsize = {o["num"]: o["vsize"] for o in objs}

    # full initialised data images (0-based, no 0x28b8 cut)
    obj2, _ = origbuild.le_object_data(1)   # idx0 1-based? le_object_data takes idx0 0-based -> obj2 = idx0 1
    obj4, _ = origbuild.le_object_data(3)   # obj4 = idx0 3
    img = bytearray(SEGLEN)
    img[0:len(obj2)] = obj2[:min(len(obj2), SEGLEN)]
    o4 = OBJ_DG_BASE[4]
    img[o4:o4 + len(obj4)] = obj4[:max(0, SEGLEN - o4)]

    # collect data-source fixups: DGROUP offset -> (target_obj, target_off, additive)
    relocs = {}
    for (src_lin, stype, ttype, tobj, toff, add, pg) in fixups:
        objn = src_object(src_lin)
        if objn is None or objn == 1:
            continue                      # code sources handled by the blob
        if src_lin >= OBJ_SRC_BASE[objn] + vsize.get(objn, 0):
            continue
        if ttype != 0 or tobj is None:
            continue                      # only internal (object) targets are pointers we relocate
        dg = (src_lin - OBJ_SRC_BASE[objn]) + OBJ_DG_BASE[objn]
        if 0 <= dg <= SEGLEN - 4:
            relocs[dg] = (tobj, toff or 0, add or 0)

    open(os.path.join(GEN, "dgroup_full.bin"), "wb").write(img)

    # emit dgroup.s: incbin slices between fixups, .long __obj<N>+off at each fixup
    binpath = os.path.join(GEN, "dgroup_full.bin").replace("\\", "/")
    lines = ["/* generated by tools/port_dgroup.py -- DGROUP image with data pointers relocated */",
             "    .data", "    .balign 16", "    .globl %s__dgroup" % US, "%s__dgroup:" % US]
    prev = 0
    for off in sorted(relocs):
        if off > prev:
            lines.append('    .incbin "%s", 0x%x, 0x%x' % (binpath, prev, off - prev))
        tobj, toff, add = relocs[off]
        e = "%s__obj%d + 0x%x" % (US, tobj, toff)
        if add:
            e += " + 0x%x" % add
        lines.append("    .long %s" % e)
        prev = off + 4
    if prev < SEGLEN:
        lines.append('    .incbin "%s", 0x%x, 0x%x' % (binpath, prev, SEGLEN - prev))
    lines += ["", "    .globl %s__obj2" % US, "    .set %s__obj2, %s__dgroup + 0x0" % (US, US),
              "    .globl %s__obj3" % US, "    .set %s__obj3, %s__dgroup + 0x13e60" % (US, US),
              "    .globl %s__obj4" % US, "    .set %s__obj4, %s__dgroup + 0x14a60" % (US, US)]
    if not US:                                  # ELF-only note; MinGW/COFF as rejects it
        lines.append('    .section .note.GNU-stack,"",@progbits')
    lines.append("")
    open(os.path.join(GEN, "dgroup_fixed.s"), "w").write("\n".join(lines))
    print("dgroup image %d bytes; data pointers relocated: %d -> %s"
          % (SEGLEN, len(relocs), os.path.join(GEN, "dgroup_fixed.s")))

if __name__ == "__main__":
    main()
