#!/usr/bin/env python3
"""port_data.py -- generate the DGROUP data model for the native port (branch `port`).

The decompiled globals are not independent variables: they are views into ONE contiguous
data segment (DGROUP) at fixed offsets, and many OVERLAP (e.g. g_syndicate_owner is literally
g_syndicate_recs + 2). The DOS build gets this right via tools/mkdata.py's data image; this
reproduces the same layout for a native link so the globals alias correctly.

Emits into port/gen/:
  dgroup.bin   -- the initialised DGROUP image: OBJECT2 | zero | OBJECT4 | zero, sized to the
                  highest referenced global. Same layout as mkdata.py.
  globals.s    -- one `.incbin dgroup.bin` blob, then for every referenced global a
                  `.set g_xxx, __dgroup + <addr>` absolute symbol. Overlapping globals resolve
                  to the same memory -> correct aliasing. Linked instead of the BSS placeholders.

Layout (DGROUP offset == the address baked into the original code), from mkdata.py:
  [0x00000, 0x0d000)  OBJECT2 (initialised, 53248 B)
  [0x0d000, 0x14a60)  zero    (OBJ2 BSS tail + OBJ3 BSS)
  [0x14a60, 0x30a60)  OBJECT4 (initialised, 114688 B)
  [0x30a60, seglen)   zero    (BSS tail + outliers)

NOTE: data-internal pointers (the tbl_* string tables and any data->data pointer) still need a
runtime fixup pass (add the DGROUP base) for fully-correct values -- a later step. This lands the
LAYOUT and ALIASING, which is the prerequisite for everything.
"""
import glob, re, os, json, struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "port", "gen"); os.makedirs(GEN, exist_ok=True)
OBJ2 = os.path.join(ROOT, "inputs", "SYNDICAT_MAIN_OBJECT2.linear.bin")
OBJ4 = os.path.join(ROOT, "inputs", "SYNDICAT_MAIN_OBJECT4.linear.bin")
OBJ4_BASE = 0x14a60

def referenced_globals():
    names = set()
    for p in glob.glob(os.path.join(ROOT, "src", "**", "*.c"), recursive=True):
        for m in re.findall(r"\bg_[0-9a-zA-Z_]+", open(p, encoding="utf-8", errors="ignore").read()):
            names.add(m)
    return names

def addr_of(name, reg):
    """Registry-first (semantic names), else the leading hex of a g_<hex> name."""
    if name in reg:
        return int(reg[name]["addr"], 16)
    m = re.match(r"g_([0-9a-fA-F]+)[a-z]*$", name)   # hex core; trailing typed-view letters ignored
    if m:
        try: return int(m.group(1), 16)
        except ValueError: return None
    return None

def main():
    reg = json.load(open(os.path.join(ROOT, "manifest", "globals.json")))
    names = referenced_globals()
    placed, skipped = {}, []
    for n in sorted(names):
        a = addr_of(n, reg)
        if a is None: skipped.append(n)
        else: placed[n] = a
    seglen = (max(placed.values()) + 0x1000) & ~0xfff        # cover the highest global, page-round
    seglen = max(seglen, 0x109110)
    # build the DGROUP image
    img = bytearray(seglen)
    o2 = open(OBJ2, "rb").read(); img[0:len(o2)] = o2
    o4 = open(OBJ4, "rb").read(); img[OBJ4_BASE:OBJ4_BASE + len(o4)] = o4
    open(os.path.join(GEN, "dgroup.bin"), "wb").write(img)
    # emit globals.s
    with open(os.path.join(GEN, "globals.s"), "w") as w:
        w.write("/* generated by tools/port_data.py -- DGROUP image + globals placed at true offsets */\n")
        w.write("    .section .data\n    .balign 16\n    .global __dgroup\n__dgroup:\n")
        w.write('    .incbin "%s"\n\n' % os.path.join(GEN, "dgroup.bin").replace("\\", "/"))
        for n, a in sorted(placed.items(), key=lambda kv: kv[1]):
            w.write("    .global %s\n    .set %s, __dgroup + 0x%x\n" % (n, n, a))
        # skipped/ambiguous globals: define as standalone BSS placeholders so the link
        # completes (their true DGROUP offset is unresolved -- typed-view aliases like
        # g_pool_a_free_v, g_5056fp2; correctness is a follow-up). Not placed in the image.
        if skipped:
            w.write("\n    .section .bss\n    .balign 16\n")
            for n in sorted(skipped):
                w.write("    .global %s\n%s:\n    .zero 256\n" % (n, n))
    # emit a GNU-stack note so the linker stops warning about executable stack
    with open(os.path.join(GEN, "globals.s"), "a") as w:
        w.write('\n    .section .note.GNU-stack,"",@progbits\n')
    print("DGROUP image: %d bytes (0x%x); OBJECT2 @0, OBJECT4 @0x%x" % (seglen, seglen, OBJ4_BASE))
    print("globals placed: %d  (skipped/ambiguous: %d)" % (len(placed), len(skipped)))
    if skipped: print("  skipped:", skipped[:12])
    # a quick aliasing self-check
    for a_name, b_name in [("g_syndicate_owner", "g_syndicate_recs")]:
        if a_name in placed and b_name in placed:
            print("  alias check: %s @0x%x, %s @0x%x  (delta %+d)" %
                  (a_name, placed[a_name], b_name, placed[b_name], placed[a_name] - placed[b_name]))

if __name__ == "__main__":
    main()
